const loans = [{ merchant: 'TunisTech Store', due: '7 days', amount: '87.500 TND' }, { merchant: 'Dar Deco', due: '14 days', amount: '42.000 TND' }];

export default function DashboardPage() {
  return <main className="min-h-screen bg-slate-950 p-6 text-white"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-teal-300">Customer dashboard</p><h1 className="text-4xl font-black">Welcome back, Amira</h1></div><a className="rounded-full bg-white px-5 py-3 font-bold text-slate-950" href="/">Home</a></header>
    <section className="mt-8 grid gap-5 lg:grid-cols-3"><Card title="Available credit" value="612.500 TND" note="Limit 700 TND" /><Card title="Credit score" value="724" note="Low risk profile" /><Card title="KYC status" value="Approved" note="CIN, selfie, address verified" /></section>
    <section className="glass mt-8 rounded-3xl p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-2xl font-black">Identity verification</h2><p className="mt-2 text-slate-300">New clients must submit KYC. Employed clients also provide three months of bank statements.</p></div><div className="flex flex-wrap gap-3"><a className="rounded-2xl bg-teal-300 px-5 py-3 font-black text-slate-950" href="/kyc">Start or update KYC</a><a className="rounded-2xl border border-white/15 px-5 py-3 font-black text-white" href="/shop">Shop with BNPL</a></div></div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_.8fr]"><div className="glass rounded-3xl p-6"><h2 className="text-2xl font-black">Active repayments</h2><div className="mt-5 space-y-3">{loans.map((loan) => <div className="rounded-2xl bg-white/5 p-4" key={loan.merchant}><div className="flex justify-between"><b>{loan.merchant}</b><span>{loan.amount}</span></div><p className="mt-2 text-sm text-slate-400">Due in {loan.due}</p></div>)}</div></div><div className="glass rounded-3xl p-6"><h2 className="text-2xl font-black">Notifications</h2><p className="mt-4 text-slate-300">Your next installment reminder will be sent by email and in-app notification.</p><button className="mt-6 w-full rounded-2xl bg-teal-300 py-3 font-black text-slate-950">Simulate repayment</button></div></section>
  </div></main>;
}
function Card({ title, value, note }: { title: string; value: string; note: string }) { return <div className="glass rounded-3xl p-6"><p className="text-sm text-slate-400">{title}</p><p className="mt-3 text-3xl font-black">{value}</p><p className="mt-2 text-sm text-teal-200">{note}</p></div>; }
